import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Do Part Time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} page-wrapper`}>
      {/* <div className="sidebar flex"> */}
      
          <Sidebar />
        {/* </div> */}

        <main className="flex-1 overflow-y-auto" style={{ backgroundColor: '#F2F2F4' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
